# Generated by Django 4.1.3 on 2022-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
